version: '3'
services:
  #Nginx Service https://hub.docker.com/_/nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage/nginx/:/var/log/nginx

  #MySQL Service https://hub.docker.com/_/mysql
  db:
    image: mysql:8.0.12
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3307:3306"
    volumes:
      - ./storage/mysql/:/var/lib/mysql/
      - ./docker/mysql/conf.d:/etc/mysql/conf.d

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080


  #PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php
    container_name: php
    env_file:
      - ./.env
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./storage/php/:/var/log/php
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
#      - ./docker/php-fpm/pool.d/www.conf:/usr/local/etc/php-fpm.d/custom.conf
